from shell_doctest import test

test(
"""\
% {make} --no-print-directory clean all
...
% sudo ./print_enc_pass
                root    $...
...
                  tn    $...
... password entries read
"""
)
