all: mydup2 ex03-06 direct_directory_read

mydup2: mydup2.c
	cc -g mydup2.c -o mydup2 -lm -I .. ../apue.3e/lib/error.c

ex03-06: ex03-06.c
	cc -g ex03-06.c -o ex03-06 -I .. ../apue.3e/lib/error.c

direct_directory_read: direct_directory_read.c
	cc -g direct_directory_read.c -o direct_directory_read -I .. ../apue.3e/lib/error.c
