PROGS = master slave

#INCLUDES = -I ../..
#CFLAGS = -ggdb3 -std=c99

# ifeq ($(shell uname),SunOS)
#     CFLAGS += -DSOLARIS -D__EXTENSIONS__
#     LDFLAGS += -lxnet
# endif

include ../../common.mk

CFILES += ../../apue.3e/lib/ptyfork.c ../../apue.3e/lib/ttymodes.c ../../apue.3e/lib/writen.c ../../apue.3e/lib/ptyopen.c ../../apue.3e/lib/signalintr.c ../../apue.3e/lib/spipe.c
